### ISSUE TITLE
Uno Dashboard - VirtualSelect is broken

### ISSUE THREAD

**Issue by oscarfgq** [unosquare/uno-dashboard-ux#173]
## Overview 

Geo started a PR to update a library (headless UI) in Uno Dashboard but the VirstualSelect was broken as a result. We need to fix it. 

https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Funosquare%2Funo-dashboard-ux%2Fpull%2F172&data=05%7C02%7C%7Cbd12f8e3aac24c28a9ce08dc7c078279%7Ceedd1340df1a4db28a03b4cfb1fa3e9d%7C0%7C0%7C638521618916152059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WR0GfQuBjAJgnemuQcglf3du5GExfSLR7KYcctbeVAk%3D&reserved=0

## Acceptance Criteria

Fix the VirstualSelect

**Comment by geoperez** [comment]
This is never going to happen, closing the issue.
