### ISSUE TITLE
Tech Debt - Disable 'Export to CSV' button when there aren't data

### ISSUE THREAD

**Issue by geoperez** [unosquare/uno-dashboard-ux#44]
# Overview
It's necessary to disable 'Export to CSV' button when there aren't data in a table of Reporting.

NOTE: When a search is applied in a data table, the 'Export to CSV' button should be enabled.

## Considered Resolved

The 'Export to CSV' button is disabled when there isn't data in a Reporting table.

**Comment by virnieva** [comment]
Done.


![Image](https://user-images.githubusercontent.com/82036122/225045538-9214b6a2-7c02-43cf-a56d-b4d95c938e26.png)
