### ISSUE TITLE
Executive Reports - Tech Debt - Define LONG_TEXT component in Data Types of grid  - “Continue Reading…”

### ISSUE THREAD

**Issue by Brianx03** [unosquare/uno-dashboard-ux#48]
## Overview
Define LONG_TEXT component in Data Types of grid  (uno-dasboard-ux) when the text is superior of 500 chars, then in the text 3 points are added with the label “Continue Reading…”

EX. RISK MANAGEMENT TRACKER - Card 3
![Image](https://user-images.githubusercontent.com/82036122/222504518-4bfda67d-72d9-40df-9b3b-970334147e88.png)

##Considered Resolved
Three points are added with the label “Continue Reading…” in LONG_TEXT component of the Grid Data Types  (uno-dasboard-ux).

**Comment by virnieva** [comment]
The logic was change for paragraph component. This component is used only in 3 reports until now.

Done.

CLIENT ATTRITION
![Image](https://user-images.githubusercontent.com/82036122/224783964-fd3e4b26-9999-4f8a-8e2f-2529076c3163.png)


DP OFFBOARDING
![Image](https://user-images.githubusercontent.com/82036122/224780035-600ddabb-8653-4e3b-86f7-26639110dcc5.png)


DP OFFBOARDING PER ACCOUNT
![Image](https://user-images.githubusercontent.com/82036122/224780458-2a4fef4e-f485-46f3-879e-a9af45c0594d.png)
